### ISSUE TITLE
[Umbrella] Support Spark 3.2

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#1224]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

The latest major version of Spark 3.2.0 is out, Kyuubi needs to support it.

### Task list

- [ ] #1228
- [ ] #1237
- [ ] #757
- [ ] #1257
- [ ] [BUILD] Support build against Scala 2.13
- [ ] [BUILD] Default build against Spark 3.2
- [ ] [DOC] Update document to reflect the build changes
- [ ] #1225 @ulysses-you 
- [ ] https://github.com/apache/incubator-kyuubi/pull/1268
- [x] #1241
- [x] #1250

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
