### ISSUE TITLE
[Umbrella] WebUI Support for Kyuubi Server

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#1669]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

WebUI Support for Kyuubi Server gives us a user-friendly view for a running Kyuubi server or maybe historical datas

### Task list

- [ ] Basic UI Framework

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pan3793** [comment]
Postpone to 1.8, because this feature is not under rapid development, and it's not supposed to be accomplished in a short time.
