### ISSUE TITLE
[Umbrella][KPIP-6] Introduce Trino frontend

### ISSUE THREAD

**Issue by ulysses-you** [apache/kyuubi#3901]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

The main goal is: Support trino-driver and trino-client connect to Kyuubi server

Proposal: https://docs.google.com/document/d/1EQBvyrYGo-m845Kg-6jN_0jhBEdDnZ1XMWjQYXnta-I/edit?usp=sharing

#### source

- [x] #3905
- [x] Compatiable with Trino rest dto (see trino-client module) https://github.com/apache/incubator-kyuubi/issues/3934
- [x] Compatiable with Trino query id, slug and token https://github.com/apache/incubator-kyuubi/issues/3935
- [x] Parse Trino http request header https://github.com/apache/incubator-kyuubi/issues/3936
- [x] Compatible with Trino http response header
- [x] Add TrinoOperationAdapter map query statement to operation (see `io.trino.jdbc.TrinoDatabaseMetaData`) @Yikf 
   - [x] [Introduce antlr4 to parse query statement](https://github.com/apache/incubator-kyuubi/issues/3926) 
   - [x] [Separate Trino lexer file](https://github.com/apache/kyuubi/pull/4098) 
   - [x] [Support `get catalogs` adapter](https://github.com/apache/kyuubi/pull/4048)
   - [x] [Support `get schemas` adapter](https://github.com/apache/kyuubi/issues/4029) 
   - [x] [Support `get tables` adapter](https://github.com/apache/kyuubi/issues/4080)
   - [x] [Support `get columns` adapter](https://github.com/apache/kyuubi/issues/4140)
   - [x] [Trino does not implement get functions](https://github.com/trinodb/trino/blob/master/client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java#L1454)
   - [x] [Support `get table types` adapter](https://github.com/apache/kyuubi/pull/4054)
   - [x] [Support `get primary keys` adapter](https://github.com/apache/kyuubi/issues/4320)
   - [x] [Trino does not implement get cross reference](https://github.com/trinodb/trino/blob/master/client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java#L1106)
   - [x] [Support `get type info` adapter](https://github.com/apache/kyuubi/pull/4066)
   - [x] set client info (do not need since it's set to http header)
   - [x] execute query
- [x] Support create query https://github.com/apache/kyuubi/pull/4232
- [x] Support get query status
- [x] Support delete query
- [x] https://github.com/apache/kyuubi/pull/4323
- [x] https://github.com/apache/kyuubi/pull/4328
- [x] Support replace `preparedStatement` for Trino-jdbc

####  integration test

- [ ] Add Trino-cli it
- [ ] Add Trino-driver it
   - [x] get catalogs
   - [x] get schemas
   - [x] get tables
   - [ ] get columns
   - [ ] get functions
   - [ ] get table types
   - [ ] get primary keys
   - [ ] get cross reference
   - [x] get type info
   - [ ] set client info 
   - [x] execute query

#### docs

- [x] Trino frontend quick start https://github.com/apache/kyuubi/pull/4345

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by ulysses-you** [comment]
cc @iodone @Yikf @yanghua @cxzl25 welcome to contribution

**Comment by iodone** [comment]
can you assign this issue to me?

**Comment by yaooqinn** [comment]
the subtask of `Introduce antlr4 to parse query statement` seems to extend the scope of this umbrella a lot, do we need a design doc for it?

**Comment by ulysses-you** [comment]
According to It's scope, it is actuall not the subtask of this umbrella .. What I expected is a pr just for parsing Trino statement and only used for something like `KyuubiTrinoSessionImpl`, not a custom precedure for Kyuubi server and something else.

**Comment by yehere** [comment]
Is it necessary to supplement multi sql and test

**Comment by ulysses-you** [comment]
@yehere it depends on the scope of your pr. in general, ut is necessary

**Comment by ulysses-you** [comment]
closed since almost issues have been solved
