### ISSUE TITLE
[Umbrella] Apache Kyuubi Graduation Tasks

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4020]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

The ASF board has approved a resolution to graduate Kyuubi into a full **T**op **L**evel **P**roject. Thanks to everyone for your help to get to this point.

To transition from the Apache Incubator to a new TLP, there's a few action items we need to do to complete the transition. These are identified by https://incubator.apache.org/guides/transferring.html#life_after_graduation.

### Task list

- Update Incubator status records
  - [x] Update the incubator status file (in svn)
        https://svn.apache.org/repos/asf/incubator/public/trunk/content/projects/kyuubi.xml
  - [x] Update podling status page
        https://incubator.apache.org/projects/
        https://incubator.apache.org/projects/kyuubi.html
        https://svn.apache.org/repos/asf/incubator/public/trunk/content/podlings.xml

- Source repo changes
  - [x] Create JIRA ticket [INFRA-24026](https://issues.apache.org/jira/browse/INFRA-24026) to request ASF Infra remove "incubator-" prefix of git repos
        https://github.com/apache/incubator-kyuubi
        https://github.com/apache/incubator-kyuubi-website
  - [x] Create JIRA ticket [INFRA-24029](https://issues.apache.org/jira/browse/INFRA-24029) to request ASF Infra move dist folder in SVN repositories from the incubator to other locations
        old: https://dist.apache.org/repos/dist/release/incubator/kyuubi
        new: https://dist.apache.org/repos/dist/release/kyuubi
  - [x] Post announcement to dev list telling everyone the repo is about repos renaming
        https://lists.apache.org/thread/vvs1p8bgxpsp6nldyrd7gd1j0or1wg7n
  - [x] Post an announcement containing instructions for developers describing how to change their git remotes.
        https://lists.apache.org/thread/vvs1p8bgxpsp6nldyrd7gd1j0or1wg7n (same as above)
  - [x] Update website, pom.xml, and other resources to point to the new repository location
  - [x] https://github.com/apache/kyuubi/pull/4161

- Source code
  - [x] Remove "Incubating" from source code
  - [x] Remove DISCLAIMER from git repo
  - [x] Remove MATURITY.md from git repo
  - [x] Update Release scripts and template
  - [x] Update GitHub CI workflows
  - [x] Update scripts under dev folder

- Websites
  - [x] Remove incubating/podding related resources from the website.
  - [x] Update the process for becoming a committer or joining PMC.

- Ecosystem
  - [x] Remove Incubating from third party projects, including Zeppelin, DBeaver
        https://github.com/apache/zeppelin/pull/4540
        https://github.com/dbeaver/dbeaver/pull/18575
        https://github.com/housepower/spark-clickhouse-connector/pull/209

**Comment by turboFei** [comment]
cc @lightning-L  could you help address the source code part tasks?

**Comment by lightning-L** [comment]
> cc @lightning-L could you help address the source code part tasks?

ok

**Comment by lightning-L** [comment]
I will submit a follow-up PR to close remaining source code tasks

**Comment by yaooqinn** [comment]
we shall also update the process for becoming a committer or pmc

**Comment by bowenliang123** [comment]
Correcting grammar and spelling  mistakes  in settings page of docs  in https://github.com/apache/kyuubi/pull/4161 .

**Comment by pan3793** [comment]
Thanks all!
