### ISSUE TITLE
[Subtask] Support GetTypeInfo for Trino Fe

### ISSUE THREAD

**Issue by Yikf** [apache/kyuubi#4065]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

Support GetTypeInfo for Trino Fe

### Parent issue

https://github.com/apache/kyuubi/issues/3901

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
