### ISSUE TITLE
[Umbrella] Kyuubi Official Docker Image

### ISSUE THREAD

**Issue by ulysses-you** [apache/kyuubi#4158]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Currently, Kyuubi has a master-snapshot image tag in docker hub which is maintained by the Kyuubi community. The original idea is, the snapshot tag can be used to help test Kyuubi on k8s with Github Action and also improve the engine test coverage. It is not stable and not an official release tag.

However, I saw that some end users already used this unstable tag due to the fact we did not push a tag during release.

Docker Official Image is the official image of docker hub which is used by many popular apache projects, e.g., Flink, Zookeeper, Spark(WIP).

I think we can also go ahead with this way.

More details see the proposal:
https://docs.google.com/document/d/1g3FKSwcLmGhU6F2pwSZPqWjZctXUOEq_F4NTqnXNzlA/edit?usp=sharing.

### Task list

- [ ] Create a new repo `apache/kyuubi-docker`
- [ ] Maintain Dockerfile in new repo according to the release tag using DOI style
- [ ] Make Kyuubi docker image work at https://hub.docker.com/_/kyuubi
- [ ] Improve related docs

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by dnskr** [comment]
@ulysses-you  Should we close this issue as completed?
