### ISSUE TITLE
[Umbrella] Suppors LakeSoul integration

### ISSUE THREAD

**Issue by SteNicholas** [apache/kyuubi#4355]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

[LakeSoul](https://github.com/meta-soul/LakeSoul) implements incremental upserts for both row and column and allows concurrent updates. LakeSoul uses LSM-Tree like structure to support updates on hash partitioning table with primary key, and achieve very high write throughput (30MB/s/core) on cloud object store like S3 while providing optimized merge on read performance. LakeSoul scales metadata management and achieves ACID control by using PostgreSQL. LakeSoul provides tools to ingest CDC and log streams automatically in a zero-ETL style. Kyuubi could support the integration with LakeSoul.

### Task list

Suppors LakeSoul integration.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by Asakiny** [comment]
Hi, @SteNicholas  LakeSoul can be integrated in Kyuubi now, both support Spark and Flink SQL Query Engine.

Please refer to : https://lakesoul-io.github.io/docs/Usage%20Docs/setup-kyuubi,

Maybe we could add docs to Kyuubi.

**Comment by SteNicholas** [comment]
@Asakiny, could you add document of LakeSoul integration in Kyuubi docs?
