### ISSUE TITLE
[Umbrella] Fully Security Support Apache Hudi via Spark Authz Plug-in

### ISSUE THREAD

**Issue by yaooqinn** [apache/kyuubi#4499]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Fully Security Support Apache Hudi via Spark Authz Plug-in

### Task list

- [ ] List all custom Hudi commands and queries
- [ ] Authz
- [ ] Data Masking
- [ ] Row Filtering

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
