### ISSUE TITLE
[Umbrella] Add rest api for OperationsResource and SessionsResource in kyuubi-rest-client SDK

### ISSUE THREAD

**Issue by turboFei** [apache/kyuubi#4539]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

It is helpful to leverage rest api.

### Task list

- OperationsRestApi
- SessionsRestApi
### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by davidyuan1223** [comment]
I prefer try to resolve this issue

**Comment by turboFei** [comment]
@davidyuan1223 sorry，this one is duplicate with @davidyuan1223

**Comment by turboFei** [comment]
close this one, duplicate with #4602
