### ISSUE TITLE
[Umbrella] Kyuubi Spark Authz extension supports Spark 3.4

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#4867]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Make Kyuubi Spark Authz extension supports Spark 3.4.

### Task list

- [x] identifier case insensitive in Spark 3.4 (with lowercased identifier)

- [x] Iceberg support
  - [x] https://github.com/apache/kyuubi/pull/4866
  - [x] Iceberg supports Spark 3.4

- [x] #4902

- [x] Changes in plans
  - #4869 for ut CreateTable / CreateTableAsSelect / ReplaceTable / ReplaceTableAsSelect 
  - #4871 for ut CreateNamespace
  - #4900 for ut "DropTable"
  - #4903 for listDatabases

- [x] deprecated ResolvedDbObjectNameTableExtractor
  - [x]  #4869  for ut "Extracting table info with ResolvedDbObjectNameTableExtractor"
  - [x] #4871 for ut "Extracting database info with ResolvedDBObjectNameDatabaseExtractor"

- [x] adapt data masking in DataMaskingForHiveParquetSuite
  - [x] ut "org.apache.kyuubi.plugin.spark.authz.ranger.datamasking.DataMaskingForHiveParquetSuite"

- [x] adapt row filtering in RowFilteringForHiveParquetSuite
  - [x] ut "org.apache.kyuubi.plugin.spark.authz.ranger.rowfiltering.RowFilteringForHiveParquetSuite"

- [x] no exeption thrown
  - [x] ut "auth: databases"
  - [x] ut "auth: functions"
  - [x] ut "auth: databases"

- [x] show objects with filtering
  - [x] ut "show databases"
  - [x] ut "show functions"
  - [x] ut "show columns"
  - [x] ut "show table extended"
  - [x] ut "[KYUUBI #3608] Support {OWNER} variable for queries"
  - [x] and 4 other tests in RangerSparkExtensionSuite

- other
  - [x] ut "[KYUUBI #3226] RuleAuthorization: Should check privileges once only." w/ HiveCatalogRangerSparkExtensionSuite
  - [x] ut "[KYUUBI #3226]: Another session should also check even if the plan is cached." w/ HiveCatalogRangerSparkExtensionSuite

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
cc @yaooqinn @pan3793 @packyan @Yikf @zhouyifan279 @packyan

**Comment by bowenliang123** [comment]
[SPARK-40020][SQL] Centralize the code of qualifying identifiers in SessionCatalog
https://issues.apache.org/jira/browse/SPARK-40020

with PR https://github.com/apache/spark/pull/37415.

This issue/PR qualifies identifiers and makes the table field  of TableIdentifier lower case with false as the default value of the  `spark.sql.caseSensitive` config. This impacts greatly to the Authz plugin and the lineage plugin.

Shall we turn the assertion for table names case insensitive or make all the table used in lower case?

@yaooqinn @pan3793 @iodone @Yikf @zhouyifan279 @wForget

**Comment by pan3793** [comment]
@bowenliang123 is this completed?

**Comment by bowenliang123** [comment]
Almost there. But Ranger's support of `ReplaceData` (for iceberg) #4916  is still under way. We may leave it behind.

**Comment by Yikf** [comment]
A question, which is perhaps unrelated to the issue, do we plan to support Apache Hudi?

**Comment by yaooqinn** [comment]
> A question, which is perhaps unrelated to the issue, do we plan to support Apache Hudi?

yes, we gonna support hudi. This can be done either through a built-in method or via an extensible approach using JSON specifications.

**Comment by pan3793** [comment]
Close as completed
