### ISSUE TITLE
[Umbrella] Kyuubi Spark lineage extension supports Spark 3.4

### ISSUE THREAD

**Issue by iodone** [apache/kyuubi#4868]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Make Kyuubi Spark lineage extension supports Spark 3.4.

### Task list
- [x] #4925 
- [x] #5170

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
@iodone is this completed?

**Comment by iodone** [comment]
> @iodone is this completed?

In development.

**Comment by pan3793** [comment]
Thanks for your great work! @iodone
