### ISSUE TITLE
[Subtask] Allow use dynamic Scala binary version in Maven module's artifactId suffix 

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#5177]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Change hardcoded Scala's version 2.12 in Maven module's artifactId to placeholder scala.binary.version which is defined in project parent pom as 2.12

### Parent issue

#3163

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.
