### ISSUE TITLE
[Umbrella] Support OAuth2 Authentication in Thrift/REST API

### ISSUE THREAD

**Issue by zhouyifan279** [apache/kyuubi#5208]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

OAuth2 is widely used in online service.  Kyuubi should support it.

### Task list

- [ ] Support OAuth2 Authentication in Thrift API
- [ ] Support OAuth2 Authentication in HTTP API

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by yaooqinn** [comment]
https://github.com/apache/kyuubi/issues/1684 duplicates

**Comment by pan3793** [comment]
@zhouyifan279 you may want to create and add the sub-task into https://github.com/apache/kyuubi/issues/5357

**Comment by synchris** [comment]
What's the status development of this feature. As I am interested in implementing it.
