### ISSUE TITLE
[Umbrella] Support Hudi in Authz

### ISSUE THREAD

**Issue by AngersZhuuuu** [apache/kyuubi#5285]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Kyuubi authz support hoodie sql

### Task list

- [x] #5284
- [x] #5359
- [x] #5360
- [x] #5361 
- [x] #5446
- [x] #5447
- [x] #5479
- [x] #5457
- [x] #5452
- [x] #5478
- [x] #5455 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by AngersZhuuuu** [comment]
ping @yaooqinn Like this?

**Comment by yaooqinn** [comment]
yeah, thank you @AngersZhuuuu
