### ISSUE TITLE
[Umbrella][V2] Kyuubi server pick task from metadata db with priority 

### ISSUE THREAD

**Issue by zwangsheng** [apache/kyuubi#5326]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Kyuubi server pick task from metadata db with priority.

### Task list

- [x] #5327 
- [x] #5328

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by zwangsheng** [comment]
Close due to finish all sub-task
