### ISSUE TITLE
[Umberella] Support Paimon in Authz

### ISSUE THREAD

**Issue by bowenliang123** [apache/kyuubi#5470]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

Introduce Paimon support in Kyuubi Authz plugin.

Apache Paimon is an incubating Apache project of data lake platform for high-speed data ingestion, changelog tracking and efficient real-time analytics.

### Task list

Paimon Spark 3 Reference: https://paimon.apache.org/docs/master/engines/spark3/

- DDL Create Tables:
  - [x] Create Table: #5462
  - [ ] Create Partitioned Table: https://paimon.apache.org/docs/master/how-to/creating-tables/#partitioned-tables
  - [ ] Create Table As: https://paimon.apache.org/docs/master/how-to/creating-tables/#create-table-as
- DDL Alter Tables : https://paimon.apache.org/docs/master/how-to/altering-tables
  - [ ] Changing/Adding Table Properties
  - [ ] Rename Table Name
  - [ ] Removing Table Properties
  - [ ] Adding New Columns
  - [ ] Renaming Column Name
  - [ ] Dropping Columns
  - [ ] Changing Column Nullability
  - [ ] Changing Column Comment
  - [ ] Adding Column Position
  - [ ] Changing Column Position
  - [ ] Changing Column Type
  - [ ] Adding watermark
  - [ ] Dropping watermark
  - [ ] Changing watermark
- DML:
  - [ ] Insert Table
  - [ ] Query Table
    - [ ] Batch Time Travel: https://paimon.apache.org/docs/master/how-to/querying-tables/#batch-time-travel
  - [ ] Update Table
- Management procedures:
  - [ ] #5430
     - [ ] Rollback to snapshot: https://paimon.apache.org/docs/master/maintenance/manage-snapshots/#rollback-to-snapshot

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [x] No. I cannot submit a PR at this time.

**Comment by davidyuan1223** [comment]
hello, i want try this issue, but i'm not sure how to improve it, this code is a createTableAsSql for paimon
```
  test("CreateTableAs") {
    withCleanTmpResources(Seq((s"$catalogV2.$namespace1.$table1", "table"),
      (s"$catalogV2.$namespace1.$table2", "table"))) {
      doAs(
        admin,
        sql(
          s"""
             |CREATE TABLE IF NOT EXISTS $catalogV2.$namespace1.$table1
             |(id int, name string, city string)
             |USING paimon
             |OPTIONS (
             |  primaryKey = 'id'
             |)
             |""".stripMargin
        )
      )
      interceptContains[AccessControlException] {
        doAs(
          someone,
          sql(
            s"""
               |CREATE TABLE IF NOT EXISTS $catalogV2.$namespace1.$table2
               |USING PAIMON
               |AS
               |SELECT * FROM $catalogV2.$namespace1.$table1
               |""".stripMargin
          )
        )
      }(s"does not have [select] privilege on [$table1/id]")
    }
  }
```
But when i try admin to execute the createTableAs Sql, the authz also will print exception, like `user [admin] does not have [select] privilege on [$table1/id]`

**Comment by bowenliang123** [comment]
> hello, i want try this issue, but i'm not sure how to improve it, this code is a createTableAsSql for paimon
> 
> ```
>   test("CreateTableAs") {
>     withCleanTmpResources(Seq((s"$catalogV2.$namespace1.$table1", "table"),
>       (s"$catalogV2.$namespace1.$table2", "table"))) {
>       doAs(
>         admin,
>         sql(
>           s"""
>              |CREATE TABLE IF NOT EXISTS $catalogV2.$namespace1.$table1
>              |(id int, name string, city string)
>              |USING paimon
>              |OPTIONS (
>              |  primaryKey = 'id'
>              |)
>              |""".stripMargin
>         )
>       )
>       interceptContains[AccessControlException] {
>         doAs(
>           someone,
>           sql(
>             s"""
>                |CREATE TABLE IF NOT EXISTS $catalogV2.$namespace1.$table2
>                |USING PAIMON
>                |AS
>                |SELECT * FROM $catalogV2.$namespace1.$table1
>                |""".stripMargin
>           )
>         )
>       }(s"does not have [select] privilege on [$table1/id]")
>     }
>   }
> ```
> 
> But when i try admin to execute the createTableAs Sql, the authz also will print exception, like `user [admin] does not have [select] privilege on [$table1/id]`

Hi, I'm not reproducing the case you mentioned. And #5590 is raised for it, you may have a check on this.
If you still encounter this issue, please submit a dedicated issue with code and logs showing the full test cases for positive and negative.

**Comment by davidyuan1223** [comment]
@bowenliang123 Paimon with Spark looks like not support chaning column nullability currently, suggest remove this subtask, the command is support with flink

**Comment by davidyuan1223** [comment]
@yaooqinn @pan3793 @bowenliang123 Currently, all subtasks have been implemented except producers. Do you think there is something missing?

**Comment by yaooqinn** [comment]
Thank you for the efforts @davidyuan1223

**Comment by davidyuan1223** [comment]
> Thank you for the efforts [@davidyuan1223](https://github.com/davidyuan1223)

If there are no missing subtasks, then I will continue to complete the subsequent subtasks.

**Comment by davidyuan1223** [comment]
All subtasks have been implemented~~
@bowenliang123 @yaooqinn @pan3793

**Comment by yaooqinn** [comment]
I'd like to close this umbrella, and thank you for the excellent work @davidyuan1223

**Comment by bowenliang123** [comment]
Thank you all the efforts to push the coverage to Paimon! @davidyuan1223
