### ISSUE TITLE
[Umbrella] [KYUUBI#5383]Take Apart The Task For Support Spark Connect Frontend/Backend

### ISSUE THREAD

**Issue by yehere** [apache/kyuubi#5541]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

#5383 Support Spark Connect Frontend/Backend

#### Task

- [ ] Add a new Spark Connect frontend, As Kyuubi Server and Kyuubi Engine's Server, Adapt Spark connector server
  - [ ] Add basic gRpc server as frontend
  - [ ] Adapt Spark connector server
  - [ ] Support ExecutePlan
  - [ ] Support AnalyzePlan
  - [ ] Support Config
  - [ ] Support AddArtifacts
  - [ ] Support ArtifactsStatus
  - [ ] Support Interrupt
  - [ ] Support ReattachExecute
  - [ ] Support ReleaseExecute
  - [ ] Deserialize the protobuf based request, Serialize response to protobuf based
  
- [ ] Adapt Kyuubi Server's business
  - [ ] Support Service Discovery
  - [ ] Support for multiple tenants
  
- [ ] Forward Request To Kyuubi Engine
  - [ ] Kyuubi Engine support the Spark connector protocol, Based on Spark Connect frontend 

####  Integration test

To be supplemented 

#### Docs

- [ ] Kyuubi Spark Connector frontend quick start

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
