### ISSUE TITLE
[Umbrella]  Support Spark Connect Frontend/Backend 

### ISSUE THREAD

**Issue by davidyuan1223** [apache/kyuubi#6324]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

This issue is from #5383 

### Task list

- [ ] Implement Spark Connect Engine
  - [ ] compatible spark connect grpc protocl based on https://github.com/apache/spark/blob/master/connector/connect/common/src/main/protobuf/spark/connect/base.proto
  - [ ] implement a grpc client based on https://github.com/apache/spark/blob/master/connector/connect/common/src/main/scala/org/apache/spark/sql/connect/client/SparkConnectClient.scala
  - [ ] add SparkConnectFrontendService
  - [ ] add SparkConnectBackendService
  - [ ] add SparkConnectOperation and SparkConnectSession
  - [ ] add ThriftToRpcRequestParser to transform thriftRequest to rpcRequest
  - [ ] add RpcToThriftResponseParser to transform rpcResponse to thriftResponse
  - [ ] implement all operation based on grpc client
  - [ ] implement engine
  - [ ] kyuubi server could provide sparkConnectEngine
- [ ] add IT based on SparkSQLEngine
- [ ] add Docs

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
