### ISSUE TITLE
[Umbrella] Publish Kyuubi Python client (former PyHive) to PyPI

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#6325]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the proposal

This is an umbrella ticket that tracks the publishing Kyuubi Python client (former PyHive) to PyPI.

### Task list

- [x] Registry a PyPI account managed by Apache Kyuubi PMC (Done, account name is: apachekyuubi)
- [ ] Decide the package name (TODO: mailing list link)
- [ ] Set up CI
- [ ] Minimal code cleanup
- [ ] Publish to Test PyPI (verification)
- [ ] Source code release and publish binary package to PyPI

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by alexio215** [comment]
Hello, I wanted to see if this Issue was ever moved forward? Has Kyuubi pyHive been published on PyPi?

**Comment by alexio215** [comment]
Hello, I am checking in to see if there is any progress in getting pyHive published or if there is any assistance that can be offered in making it happen. Thank you very much!
